# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ukro-recruitment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Clean install dependencies
        run: |
          npm ci --production=false
          rm -rf .next

      - name: Build Next.js application
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: production

      - name: Prepare standalone deployment
        run: |
          echo "📦 Preparing standalone deployment..."
          mkdir -p deploy

          # Copy standalone server
          cp -r .next/standalone/* deploy/

          # Copy static assets
          mkdir -p deploy/.next/static
          cp -r .next/static/* deploy/.next/static/

          # Copy public folder
          if [ -d "public" ]; then
            cp -r public deploy/
          fi

          # Copy package.json for reference
          cp package.json deploy/

          echo "✅ Standalone deployment prepared"

      - name: Zip standalone artifact for deployment
        run: |
          cd deploy
          zip -r ../release.zip ./*
          cd ..
          echo "✅ Deployment package created: $(du -h release.zip | cut -f1)"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Remove oryx-manifest.toml to prevent Oryx interference
        run: |
          rm -f oryx-manifest.toml
          rm -f .oryx_manifest.toml
          echo "✅ Oryx manifest files removed (if existed)"

      - name: Create startup configuration
        run: |
          echo "node server.js" > startup.sh
          chmod +x startup.sh
          echo "✅ Startup script created"

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ukro-recruitment"
          # Removed slot-name - deploy to main slot
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6AF59876D5CD4F86B63B69F2C3D40407 }}
